----------------------------------------------------------------
-- File : test_rs_encoding_decoding.vhd
-- Created : 02.12.2025
-- Author : Matthias Fuchs
-- Project Name : HW/SW Project TM
-- Description : Used the block diagram to add R/S encoder and decoder; this test bench testes the encoding/decoding
----------------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- leere entity
entity test_rs_encoding_decoding is
end entity test_rs_encoding_decoding;

architecture behavioral of test_rs_encoding_decoding is

  -- Moduldeklaration
  component design_1_wrapper is
    port (

    clk_i_0 : in STD_LOGIC;
    data_valid_o_0 : out STD_LOGIC;
    data_valid_o_1 : out STD_LOGIC;
    encoder_done_flag_o_0 : out STD_LOGIC;
    input_byte_i_0 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    output_byte_o_0 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    reset_i_0 : in STD_LOGIC;
    
    output_byte_o_1 : out STD_LOGIC_VECTOR ( 7 downto 0 )
    );
  end component;

  -- input
  signal clk_i_0   : std_logic := '0';
  signal reset_i_0 : std_logic := '1';
  signal encoder_done_flag_o_0 : std_logic;
  signal data_valid_o_0, data_valid_o_1 : std_logic;
  
    signal output_byte_o_1 : STD_LOGIC_VECTOR ( 7 downto 0 );

  -- output
  signal input_byte_i_0, output_byte_o_0: STD_LOGIC_VECTOR ( 7 downto 0 );

begin
  clk_i_0   <= not clk_i_0  after 5 ns;
  reset_i_0 <= '0', '1' after 41.44 us; -- erzeugt Resetsignal: --__

  -- Modulinstatziierung
  dut : design_1_wrapper
    port map (
      clk_i_0       => clk_i_0,
      reset_i_0     => reset_i_0,
      data_valid_o_1 => data_valid_o_1,

      encoder_done_flag_o_0     => encoder_done_flag_o_0,
      data_valid_o_0 => data_valid_o_0,
      input_byte_i_0  => input_byte_i_0,
      output_byte_o_0  => output_byte_o_0,
      output_byte_o_1  => output_byte_o_1
      );
      
     process
    begin
        -- generated using generateEncoder_tb_data.py
        input_byte_i_0 <= x"00";
        wait for 160 ns;
        input_byte_i_0 <= x"01";
        wait for 160 ns;
        input_byte_i_0 <= x"02";
        wait for 160 ns;
        input_byte_i_0 <= x"03";
        wait for 160 ns;
        input_byte_i_0 <= x"04";
        wait for 160 ns;
        input_byte_i_0 <= x"05";
        wait for 160 ns;
        input_byte_i_0 <= x"06";
        wait for 160 ns;
        input_byte_i_0 <= x"07";
        wait for 160 ns;
        input_byte_i_0 <= x"08";
        wait for 160 ns;
        input_byte_i_0 <= x"09";
        wait for 160 ns;
        input_byte_i_0 <= x"0a";
        wait for 160 ns;
        input_byte_i_0 <= x"0b";
        wait for 160 ns;
        input_byte_i_0 <= x"0c";
        wait for 160 ns;
        input_byte_i_0 <= x"0d";
        wait for 160 ns;
        input_byte_i_0 <= x"0e";
        wait for 160 ns;
        input_byte_i_0 <= x"0f";
        wait for 160 ns;
        input_byte_i_0 <= x"10";
        wait for 160 ns;
        input_byte_i_0 <= x"11";
        wait for 160 ns;
        input_byte_i_0 <= x"12";
        wait for 160 ns;
        input_byte_i_0 <= x"13";
        wait for 160 ns;
        input_byte_i_0 <= x"14";
        wait for 160 ns;
        input_byte_i_0 <= x"15";
        wait for 160 ns;
        input_byte_i_0 <= x"16";
        wait for 160 ns;
        input_byte_i_0 <= x"17";
        wait for 160 ns;
        input_byte_i_0 <= x"18";
        wait for 160 ns;
        input_byte_i_0 <= x"19";
        wait for 160 ns;
        input_byte_i_0 <= x"1a";
        wait for 160 ns;
        input_byte_i_0 <= x"1b";
        wait for 160 ns;
        input_byte_i_0 <= x"1c";
        wait for 160 ns;
        input_byte_i_0 <= x"1d";
        wait for 160 ns;
        input_byte_i_0 <= x"1e";
        wait for 160 ns;
        input_byte_i_0 <= x"1f";
        wait for 160 ns;
        input_byte_i_0 <= x"20";
        wait for 160 ns;
        input_byte_i_0 <= x"21";
        wait for 160 ns;
        input_byte_i_0 <= x"22";
        wait for 160 ns;
        input_byte_i_0 <= x"23";
        wait for 160 ns;
        input_byte_i_0 <= x"24";
        wait for 160 ns;
        input_byte_i_0 <= x"25";
        wait for 160 ns;
        input_byte_i_0 <= x"26";
        wait for 160 ns;
        input_byte_i_0 <= x"27";
        wait for 160 ns;
        input_byte_i_0 <= x"28";
        wait for 160 ns;
        input_byte_i_0 <= x"29";
        wait for 160 ns;
        input_byte_i_0 <= x"2a";
        wait for 160 ns;
        input_byte_i_0 <= x"2b";
        wait for 160 ns;
        input_byte_i_0 <= x"2c";
        wait for 160 ns;
        input_byte_i_0 <= x"2d";
        wait for 160 ns;
        input_byte_i_0 <= x"2e";
        wait for 160 ns;
        input_byte_i_0 <= x"2f";
        wait for 160 ns;
        input_byte_i_0 <= x"30";
        wait for 160 ns;
        input_byte_i_0 <= x"31";
        wait for 160 ns;
        input_byte_i_0 <= x"32";
        wait for 160 ns;
        input_byte_i_0 <= x"33";
        wait for 160 ns;
        input_byte_i_0 <= x"34";
        wait for 160 ns;
        input_byte_i_0 <= x"35";
        wait for 160 ns;
        input_byte_i_0 <= x"36";
        wait for 160 ns;
        input_byte_i_0 <= x"37";
        wait for 160 ns;
        input_byte_i_0 <= x"38";
        wait for 160 ns;
        input_byte_i_0 <= x"39";
        wait for 160 ns;
        input_byte_i_0 <= x"3a";
        wait for 160 ns;
        input_byte_i_0 <= x"3b";
        wait for 160 ns;
        input_byte_i_0 <= x"3c";
        wait for 160 ns;
        input_byte_i_0 <= x"3d";
        wait for 160 ns;
        input_byte_i_0 <= x"3e";
        wait for 160 ns;
        input_byte_i_0 <= x"3f";
        wait for 160 ns;
        input_byte_i_0 <= x"40";
        wait for 160 ns;
        input_byte_i_0 <= x"41";
        wait for 160 ns;
        input_byte_i_0 <= x"42";
        wait for 160 ns;
        input_byte_i_0 <= x"43";
        wait for 160 ns;
        input_byte_i_0 <= x"44";
        wait for 160 ns;
        input_byte_i_0 <= x"45";
        wait for 160 ns;
        input_byte_i_0 <= x"46";
        wait for 160 ns;
        input_byte_i_0 <= x"47";
        wait for 160 ns;
        input_byte_i_0 <= x"48";
        wait for 160 ns;
        input_byte_i_0 <= x"49";
        wait for 160 ns;
        input_byte_i_0 <= x"4a";
        wait for 160 ns;
        input_byte_i_0 <= x"4b";
        wait for 160 ns;
        input_byte_i_0 <= x"4c";
        wait for 160 ns;
        input_byte_i_0 <= x"4d";
        wait for 160 ns;
        input_byte_i_0 <= x"4e";
        wait for 160 ns;
        input_byte_i_0 <= x"4f";
        wait for 160 ns;
        input_byte_i_0 <= x"50";
        wait for 160 ns;
        input_byte_i_0 <= x"51";
        wait for 160 ns;
        input_byte_i_0 <= x"52";
        wait for 160 ns;
        input_byte_i_0 <= x"53";
        wait for 160 ns;
        input_byte_i_0 <= x"54";
        wait for 160 ns;
        input_byte_i_0 <= x"55";
        wait for 160 ns;
        input_byte_i_0 <= x"56";
        wait for 160 ns;
        input_byte_i_0 <= x"57";
        wait for 160 ns;
        input_byte_i_0 <= x"58";
        wait for 160 ns;
        input_byte_i_0 <= x"59";
        wait for 160 ns;
        input_byte_i_0 <= x"5a";
        wait for 160 ns;
        input_byte_i_0 <= x"5b";
        wait for 160 ns;
        input_byte_i_0 <= x"5c";
        wait for 160 ns;
        input_byte_i_0 <= x"5d";
        wait for 160 ns;
        input_byte_i_0 <= x"5e";
        wait for 160 ns;
        input_byte_i_0 <= x"5f";
        wait for 160 ns;
        input_byte_i_0 <= x"60";
        wait for 160 ns;
        input_byte_i_0 <= x"61";
        wait for 160 ns;
        input_byte_i_0 <= x"62";
        wait for 160 ns;
        input_byte_i_0 <= x"63";
        wait for 160 ns;
        input_byte_i_0 <= x"64";
        wait for 160 ns;
        input_byte_i_0 <= x"65";
        wait for 160 ns;
        input_byte_i_0 <= x"66";
        wait for 160 ns;
        input_byte_i_0 <= x"67";
        wait for 160 ns;
        input_byte_i_0 <= x"68";
        wait for 160 ns;
        input_byte_i_0 <= x"69";
        wait for 160 ns;
        input_byte_i_0 <= x"6a";
        wait for 160 ns;
        input_byte_i_0 <= x"6b";
        wait for 160 ns;
        input_byte_i_0 <= x"6c";
        wait for 160 ns;
        input_byte_i_0 <= x"6d";
        wait for 160 ns;
        input_byte_i_0 <= x"6e";
        wait for 160 ns;
        input_byte_i_0 <= x"6f";
        wait for 160 ns;
        input_byte_i_0 <= x"70";
        wait for 160 ns;
        input_byte_i_0 <= x"71";
        wait for 160 ns;
        input_byte_i_0 <= x"72";
        wait for 160 ns;
        input_byte_i_0 <= x"73";
        wait for 160 ns;
        input_byte_i_0 <= x"74";
        wait for 160 ns;
        input_byte_i_0 <= x"75";
        wait for 160 ns;
        input_byte_i_0 <= x"76";
        wait for 160 ns;
        input_byte_i_0 <= x"77";
        wait for 160 ns;
        input_byte_i_0 <= x"78";
        wait for 160 ns;
        input_byte_i_0 <= x"79";
        wait for 160 ns;
        input_byte_i_0 <= x"7a";
        wait for 160 ns;
        input_byte_i_0 <= x"7b";
        wait for 160 ns;
        input_byte_i_0 <= x"7c";
        wait for 160 ns;
        input_byte_i_0 <= x"7d";
        wait for 160 ns;
        input_byte_i_0 <= x"7e";
        wait for 160 ns;
        input_byte_i_0 <= x"7f";
        wait for 160 ns;
        input_byte_i_0 <= x"80";
        wait for 160 ns;
        input_byte_i_0 <= x"81";
        wait for 160 ns;
        input_byte_i_0 <= x"82";
        wait for 160 ns;
        input_byte_i_0 <= x"83";
        wait for 160 ns;
        input_byte_i_0 <= x"84";
        wait for 160 ns;
        input_byte_i_0 <= x"85";
        wait for 160 ns;
        input_byte_i_0 <= x"86";
        wait for 160 ns;
        input_byte_i_0 <= x"87";
        wait for 160 ns;
        input_byte_i_0 <= x"88";
        wait for 160 ns;
        input_byte_i_0 <= x"89";
        wait for 160 ns;
        input_byte_i_0 <= x"8a";
        wait for 160 ns;
        input_byte_i_0 <= x"8b";
        wait for 160 ns;
        input_byte_i_0 <= x"8c";
        wait for 160 ns;
        input_byte_i_0 <= x"8d";
        wait for 160 ns;
        input_byte_i_0 <= x"8e";
        wait for 160 ns;
        input_byte_i_0 <= x"8f";
        wait for 160 ns;
        input_byte_i_0 <= x"90";
        wait for 160 ns;
        input_byte_i_0 <= x"91";
        wait for 160 ns;
        input_byte_i_0 <= x"92";
        wait for 160 ns;
        input_byte_i_0 <= x"93";
        wait for 160 ns;
        input_byte_i_0 <= x"94";
        wait for 160 ns;
        input_byte_i_0 <= x"95";
        wait for 160 ns;
        input_byte_i_0 <= x"96";
        wait for 160 ns;
        input_byte_i_0 <= x"97";
        wait for 160 ns;
        input_byte_i_0 <= x"98";
        wait for 160 ns;
        input_byte_i_0 <= x"99";
        wait for 160 ns;
        input_byte_i_0 <= x"9a";
        wait for 160 ns;
        input_byte_i_0 <= x"9b";
        wait for 160 ns;
        input_byte_i_0 <= x"9c";
        wait for 160 ns;
        input_byte_i_0 <= x"9d";
        wait for 160 ns;
        input_byte_i_0 <= x"9e";
        wait for 160 ns;
        input_byte_i_0 <= x"9f";
        wait for 160 ns;
        input_byte_i_0 <= x"a0";
        wait for 160 ns;
        input_byte_i_0 <= x"a1";
        wait for 160 ns;
        input_byte_i_0 <= x"a2";
        wait for 160 ns;
        input_byte_i_0 <= x"a3";
        wait for 160 ns;
        input_byte_i_0 <= x"a4";
        wait for 160 ns;
        input_byte_i_0 <= x"a5";
        wait for 160 ns;
        input_byte_i_0 <= x"a6";
        wait for 160 ns;
        input_byte_i_0 <= x"a7";
        wait for 160 ns;
        input_byte_i_0 <= x"a8";
        wait for 160 ns;
        input_byte_i_0 <= x"a9";
        wait for 160 ns;
        input_byte_i_0 <= x"aa";
        wait for 160 ns;
        input_byte_i_0 <= x"ab";
        wait for 160 ns;
        input_byte_i_0 <= x"ac";
        wait for 160 ns;
        input_byte_i_0 <= x"ad";
        wait for 160 ns;
        input_byte_i_0 <= x"ae";
        wait for 160 ns;
        input_byte_i_0 <= x"af";
        wait for 160 ns;
        input_byte_i_0 <= x"b0";
        wait for 160 ns;
        input_byte_i_0 <= x"b1";
        wait for 160 ns;
        input_byte_i_0 <= x"b2";
        wait for 160 ns;
        input_byte_i_0 <= x"b3";
        wait for 160 ns;
        input_byte_i_0 <= x"b4";
        wait for 160 ns;
        input_byte_i_0 <= x"b5";
        wait for 160 ns;
        input_byte_i_0 <= x"b6";
        wait for 160 ns;
        input_byte_i_0 <= x"b7";
        wait for 160 ns;
        input_byte_i_0 <= x"b8";
        wait for 160 ns;
        input_byte_i_0 <= x"b9";
        wait for 160 ns;
        input_byte_i_0 <= x"ba";
        wait for 160 ns;
        input_byte_i_0 <= x"bb";
        wait for 160 ns;
        input_byte_i_0 <= x"bc";
        wait for 160 ns;
        input_byte_i_0 <= x"bd";
        wait for 160 ns;
        input_byte_i_0 <= x"be";
        wait for 160 ns;
        input_byte_i_0 <= x"bf";
        wait for 160 ns;
        input_byte_i_0 <= x"c0";
        wait for 160 ns;
        input_byte_i_0 <= x"c1";
        wait for 160 ns;
        input_byte_i_0 <= x"c2";
        wait for 160 ns;
        input_byte_i_0 <= x"c3";
        wait for 160 ns;
        input_byte_i_0 <= x"c4";
        wait for 160 ns;
        input_byte_i_0 <= x"c5";
        wait for 160 ns;
        input_byte_i_0 <= x"c6";
        wait for 160 ns;
        input_byte_i_0 <= x"c7";
        wait for 160 ns;
        input_byte_i_0 <= x"c8";
        wait for 160 ns;
        input_byte_i_0 <= x"c9";
        wait for 160 ns;
        input_byte_i_0 <= x"ca";
        wait for 160 ns;
        input_byte_i_0 <= x"cb";
        wait for 160 ns;
        input_byte_i_0 <= x"cc";
        wait for 160 ns;
        input_byte_i_0 <= x"cd";
        wait for 160 ns;
        input_byte_i_0 <= x"ce";
        wait for 160 ns;
        input_byte_i_0 <= x"cf";
        wait for 160 ns;
        input_byte_i_0 <= x"d0";
        wait for 160 ns;
        input_byte_i_0 <= x"d1";
        wait for 160 ns;
        input_byte_i_0 <= x"d2";
        wait for 160 ns;
        input_byte_i_0 <= x"d3";
        wait for 160 ns;
        input_byte_i_0 <= x"d4";
        wait for 160 ns;
        input_byte_i_0 <= x"d5";
        wait for 160 ns;
        input_byte_i_0 <= x"d6";
        wait for 160 ns;
        input_byte_i_0 <= x"d7";
        wait for 160 ns;
        input_byte_i_0 <= x"d8";
        wait for 160 ns;
        input_byte_i_0 <= x"d9";
        wait for 160 ns;
        input_byte_i_0 <= x"da";
        wait for 160 ns;
        input_byte_i_0 <= x"db";
        wait for 160 ns;
        input_byte_i_0 <= x"dc";
        wait for 160 ns;
        input_byte_i_0 <= x"dd";
        wait for 160 ns;
        input_byte_i_0 <= x"df";
        wait for 160 * 37 ns;
    end process;


end architecture;