-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- File : ReedSolomonEncoder_tb.vhd
-- Created : 18.11.2025
-- Author : Matthias Fuchs
-- Project Name : HW/SW Project TM
-- Description : Testbench for R/S Encoder
-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.finite_field.all;

entity ReedSolomonEncoder_tb is
end entity ReedSolomonEncoder_tb;

architecture bhv of ReedSolomonEncoder_tb is

    component reed_solomon_encoder is
    port (
        clk_i   : in std_logic;
        reset_i : in std_logic;
        input_byte_i : in std_logic_vector (7 downto 0);

        output_byte_o : out std_logic_vector (7 downto 0);
        encoder_done_flag_o : out std_logic := '0'
    );
  end component;

    signal clk_r : STD_LOGIC := '1';
    signal reset_r : STD_LOGIC := '1';

    signal input_byte_r : std_logic_vector (7 downto 0);
    
    signal output_byte_r : std_logic_vector (7 downto 0);
    signal encoder_done_flag_r : std_logic;

begin
    dut : reed_solomon_encoder
    port map (
      clk_i       => clk_r,
      reset_i     => reset_r,

      input_byte_i=> input_byte_r,
      output_byte_o => output_byte_r,
      encoder_done_flag_o  => encoder_done_flag_r
    );

    
    clk_r <= not clk_r after 5 ns;
    process
    begin
        -- generated using generateEncoder_tb_data.py
        input_byte_r <= x"00";
        wait for 160 ns;
        input_byte_r <= x"01";
        wait for 160 ns;
        input_byte_r <= x"02";
        wait for 160 ns;
        input_byte_r <= x"03";
        wait for 160 ns;
        input_byte_r <= x"04";
        wait for 160 ns;
        input_byte_r <= x"05";
        wait for 160 ns;
        input_byte_r <= x"06";
        wait for 160 ns;
        input_byte_r <= x"07";
        wait for 160 ns;
        input_byte_r <= x"08";
        wait for 160 ns;
        input_byte_r <= x"09";
        wait for 160 ns;
        input_byte_r <= x"0a";
        wait for 160 ns;
        input_byte_r <= x"0b";
        wait for 160 ns;
        input_byte_r <= x"0c";
        wait for 160 ns;
        input_byte_r <= x"0d";
        wait for 160 ns;
        input_byte_r <= x"0e";
        wait for 160 ns;
        input_byte_r <= x"0f";
        wait for 160 ns;
        input_byte_r <= x"10";
        wait for 160 ns;
        input_byte_r <= x"11";
        wait for 160 ns;
        input_byte_r <= x"12";
        wait for 160 ns;
        input_byte_r <= x"13";
        wait for 160 ns;
        input_byte_r <= x"14";
        wait for 160 ns;
        input_byte_r <= x"15";
        wait for 160 ns;
        input_byte_r <= x"16";
        wait for 160 ns;
        input_byte_r <= x"17";
        wait for 160 ns;
        input_byte_r <= x"18";
        wait for 160 ns;
        input_byte_r <= x"19";
        wait for 160 ns;
        input_byte_r <= x"1a";
        wait for 160 ns;
        input_byte_r <= x"1b";
        wait for 160 ns;
        input_byte_r <= x"1c";
        wait for 160 ns;
        input_byte_r <= x"1d";
        wait for 160 ns;
        input_byte_r <= x"1e";
        wait for 160 ns;
        input_byte_r <= x"1f";
        wait for 160 ns;
        input_byte_r <= x"20";
        wait for 160 ns;
        input_byte_r <= x"21";
        wait for 160 ns;
        input_byte_r <= x"22";
        wait for 160 ns;
        input_byte_r <= x"23";
        wait for 160 ns;
        input_byte_r <= x"24";
        wait for 160 ns;
        input_byte_r <= x"25";
        wait for 160 ns;
        input_byte_r <= x"26";
        wait for 160 ns;
        input_byte_r <= x"27";
        wait for 160 ns;
        input_byte_r <= x"28";
        wait for 160 ns;
        input_byte_r <= x"29";
        wait for 160 ns;
        input_byte_r <= x"2a";
        wait for 160 ns;
        input_byte_r <= x"2b";
        wait for 160 ns;
        input_byte_r <= x"2c";
        wait for 160 ns;
        input_byte_r <= x"2d";
        wait for 160 ns;
        input_byte_r <= x"2e";
        wait for 160 ns;
        input_byte_r <= x"2f";
        wait for 160 ns;
        input_byte_r <= x"30";
        wait for 160 ns;
        input_byte_r <= x"31";
        wait for 160 ns;
        input_byte_r <= x"32";
        wait for 160 ns;
        input_byte_r <= x"33";
        wait for 160 ns;
        input_byte_r <= x"34";
        wait for 160 ns;
        input_byte_r <= x"35";
        wait for 160 ns;
        input_byte_r <= x"36";
        wait for 160 ns;
        input_byte_r <= x"37";
        wait for 160 ns;
        input_byte_r <= x"38";
        wait for 160 ns;
        input_byte_r <= x"39";
        wait for 160 ns;
        input_byte_r <= x"3a";
        wait for 160 ns;
        input_byte_r <= x"3b";
        wait for 160 ns;
        input_byte_r <= x"3c";
        wait for 160 ns;
        input_byte_r <= x"3d";
        wait for 160 ns;
        input_byte_r <= x"3e";
        wait for 160 ns;
        input_byte_r <= x"3f";
        wait for 160 ns;
        input_byte_r <= x"40";
        wait for 160 ns;
        input_byte_r <= x"41";
        wait for 160 ns;
        input_byte_r <= x"42";
        wait for 160 ns;
        input_byte_r <= x"43";
        wait for 160 ns;
        input_byte_r <= x"44";
        wait for 160 ns;
        input_byte_r <= x"45";
        wait for 160 ns;
        input_byte_r <= x"46";
        wait for 160 ns;
        input_byte_r <= x"47";
        wait for 160 ns;
        input_byte_r <= x"48";
        wait for 160 ns;
        input_byte_r <= x"49";
        wait for 160 ns;
        input_byte_r <= x"4a";
        wait for 160 ns;
        input_byte_r <= x"4b";
        wait for 160 ns;
        input_byte_r <= x"4c";
        wait for 160 ns;
        input_byte_r <= x"4d";
        wait for 160 ns;
        input_byte_r <= x"4e";
        wait for 160 ns;
        input_byte_r <= x"4f";
        wait for 160 ns;
        input_byte_r <= x"50";
        wait for 160 ns;
        input_byte_r <= x"51";
        wait for 160 ns;
        input_byte_r <= x"52";
        wait for 160 ns;
        input_byte_r <= x"53";
        wait for 160 ns;
        input_byte_r <= x"54";
        wait for 160 ns;
        input_byte_r <= x"55";
        wait for 160 ns;
        input_byte_r <= x"56";
        wait for 160 ns;
        input_byte_r <= x"57";
        wait for 160 ns;
        input_byte_r <= x"58";
        wait for 160 ns;
        input_byte_r <= x"59";
        wait for 160 ns;
        input_byte_r <= x"5a";
        wait for 160 ns;
        input_byte_r <= x"5b";
        wait for 160 ns;
        input_byte_r <= x"5c";
        wait for 160 ns;
        input_byte_r <= x"5d";
        wait for 160 ns;
        input_byte_r <= x"5e";
        wait for 160 ns;
        input_byte_r <= x"5f";
        wait for 160 ns;
        input_byte_r <= x"60";
        wait for 160 ns;
        input_byte_r <= x"61";
        wait for 160 ns;
        input_byte_r <= x"62";
        wait for 160 ns;
        input_byte_r <= x"63";
        wait for 160 ns;
        input_byte_r <= x"64";
        wait for 160 ns;
        input_byte_r <= x"65";
        wait for 160 ns;
        input_byte_r <= x"66";
        wait for 160 ns;
        input_byte_r <= x"67";
        wait for 160 ns;
        input_byte_r <= x"68";
        wait for 160 ns;
        input_byte_r <= x"69";
        wait for 160 ns;
        input_byte_r <= x"6a";
        wait for 160 ns;
        input_byte_r <= x"6b";
        wait for 160 ns;
        input_byte_r <= x"6c";
        wait for 160 ns;
        input_byte_r <= x"6d";
        wait for 160 ns;
        input_byte_r <= x"6e";
        wait for 160 ns;
        input_byte_r <= x"6f";
        wait for 160 ns;
        input_byte_r <= x"70";
        wait for 160 ns;
        input_byte_r <= x"71";
        wait for 160 ns;
        input_byte_r <= x"72";
        wait for 160 ns;
        input_byte_r <= x"73";
        wait for 160 ns;
        input_byte_r <= x"74";
        wait for 160 ns;
        input_byte_r <= x"75";
        wait for 160 ns;
        input_byte_r <= x"76";
        wait for 160 ns;
        input_byte_r <= x"77";
        wait for 160 ns;
        input_byte_r <= x"78";
        wait for 160 ns;
        input_byte_r <= x"79";
        wait for 160 ns;
        input_byte_r <= x"7a";
        wait for 160 ns;
        input_byte_r <= x"7b";
        wait for 160 ns;
        input_byte_r <= x"7c";
        wait for 160 ns;
        input_byte_r <= x"7d";
        wait for 160 ns;
        input_byte_r <= x"7e";
        wait for 160 ns;
        input_byte_r <= x"7f";
        wait for 160 ns;
        input_byte_r <= x"80";
        wait for 160 ns;
        input_byte_r <= x"81";
        wait for 160 ns;
        input_byte_r <= x"82";
        wait for 160 ns;
        input_byte_r <= x"83";
        wait for 160 ns;
        input_byte_r <= x"84";
        wait for 160 ns;
        input_byte_r <= x"85";
        wait for 160 ns;
        input_byte_r <= x"86";
        wait for 160 ns;
        input_byte_r <= x"87";
        wait for 160 ns;
        input_byte_r <= x"88";
        wait for 160 ns;
        input_byte_r <= x"89";
        wait for 160 ns;
        input_byte_r <= x"8a";
        wait for 160 ns;
        input_byte_r <= x"8b";
        wait for 160 ns;
        input_byte_r <= x"8c";
        wait for 160 ns;
        input_byte_r <= x"8d";
        wait for 160 ns;
        input_byte_r <= x"8e";
        wait for 160 ns;
        input_byte_r <= x"8f";
        wait for 160 ns;
        input_byte_r <= x"90";
        wait for 160 ns;
        input_byte_r <= x"91";
        wait for 160 ns;
        input_byte_r <= x"92";
        wait for 160 ns;
        input_byte_r <= x"93";
        wait for 160 ns;
        input_byte_r <= x"94";
        wait for 160 ns;
        input_byte_r <= x"95";
        wait for 160 ns;
        input_byte_r <= x"96";
        wait for 160 ns;
        input_byte_r <= x"97";
        wait for 160 ns;
        input_byte_r <= x"98";
        wait for 160 ns;
        input_byte_r <= x"99";
        wait for 160 ns;
        input_byte_r <= x"9a";
        wait for 160 ns;
        input_byte_r <= x"9b";
        wait for 160 ns;
        input_byte_r <= x"9c";
        wait for 160 ns;
        input_byte_r <= x"9d";
        wait for 160 ns;
        input_byte_r <= x"9e";
        wait for 160 ns;
        input_byte_r <= x"9f";
        wait for 160 ns;
        input_byte_r <= x"a0";
        wait for 160 ns;
        input_byte_r <= x"a1";
        wait for 160 ns;
        input_byte_r <= x"a2";
        wait for 160 ns;
        input_byte_r <= x"a3";
        wait for 160 ns;
        input_byte_r <= x"a4";
        wait for 160 ns;
        input_byte_r <= x"a5";
        wait for 160 ns;
        input_byte_r <= x"a6";
        wait for 160 ns;
        input_byte_r <= x"a7";
        wait for 160 ns;
        input_byte_r <= x"a8";
        wait for 160 ns;
        input_byte_r <= x"a9";
        wait for 160 ns;
        input_byte_r <= x"aa";
        wait for 160 ns;
        input_byte_r <= x"ab";
        wait for 160 ns;
        input_byte_r <= x"ac";
        wait for 160 ns;
        input_byte_r <= x"ad";
        wait for 160 ns;
        input_byte_r <= x"ae";
        wait for 160 ns;
        input_byte_r <= x"af";
        wait for 160 ns;
        input_byte_r <= x"b0";
        wait for 160 ns;
        input_byte_r <= x"b1";
        wait for 160 ns;
        input_byte_r <= x"b2";
        wait for 160 ns;
        input_byte_r <= x"b3";
        wait for 160 ns;
        input_byte_r <= x"b4";
        wait for 160 ns;
        input_byte_r <= x"b5";
        wait for 160 ns;
        input_byte_r <= x"b6";
        wait for 160 ns;
        input_byte_r <= x"b7";
        wait for 160 ns;
        input_byte_r <= x"b8";
        wait for 160 ns;
        input_byte_r <= x"b9";
        wait for 160 ns;
        input_byte_r <= x"ba";
        wait for 160 ns;
        input_byte_r <= x"bb";
        wait for 160 ns;
        input_byte_r <= x"bc";
        wait for 160 ns;
        input_byte_r <= x"bd";
        wait for 160 ns;
        input_byte_r <= x"be";
        wait for 160 ns;
        input_byte_r <= x"bf";
        wait for 160 ns;
        input_byte_r <= x"c0";
        wait for 160 ns;
        input_byte_r <= x"c1";
        wait for 160 ns;
        input_byte_r <= x"c2";
        wait for 160 ns;
        input_byte_r <= x"c3";
        wait for 160 ns;
        input_byte_r <= x"c4";
        wait for 160 ns;
        input_byte_r <= x"c5";
        wait for 160 ns;
        input_byte_r <= x"c6";
        wait for 160 ns;
        input_byte_r <= x"c7";
        wait for 160 ns;
        input_byte_r <= x"c8";
        wait for 160 ns;
        input_byte_r <= x"c9";
        wait for 160 ns;
        input_byte_r <= x"ca";
        wait for 160 ns;
        input_byte_r <= x"cb";
        wait for 160 ns;
        input_byte_r <= x"cc";
        wait for 160 ns;
        input_byte_r <= x"cd";
        wait for 160 ns;
        input_byte_r <= x"ce";
        wait for 160 ns;
        input_byte_r <= x"cf";
        wait for 160 ns;
        input_byte_r <= x"d0";
        wait for 160 ns;
        input_byte_r <= x"d1";
        wait for 160 ns;
        input_byte_r <= x"d2";
        wait for 160 ns;
        input_byte_r <= x"d3";
        wait for 160 ns;
        input_byte_r <= x"d4";
        wait for 160 ns;
        input_byte_r <= x"d5";
        wait for 160 ns;
        input_byte_r <= x"d6";
        wait for 160 ns;
        input_byte_r <= x"d7";
        wait for 160 ns;
        input_byte_r <= x"d8";
        wait for 160 ns;
        input_byte_r <= x"d9";
        wait for 160 ns;
        input_byte_r <= x"da";
        wait for 160 ns;
        input_byte_r <= x"db";
        wait for 160 ns;
        input_byte_r <= x"dc";
        wait for 160 ns;
        input_byte_r <= x"dd";
        wait for 160 ns;
        input_byte_r <= x"df";
        wait for 160 * 37 ns;
    end process;


end architecture;